### ISSUE TITLE
Server crash - NPE server tick loop

### ISSUE THREAD

**Issue by Terpo** [Chicken-Bones/WirelessRedstone#11]
Our server crashed today: http://pastebin.com/h9xLJ6hn

CodeChickenCore-1.7.10-1.0.4.35-universal.jar
NotEnoughItems-1.7.10-1.0.4.90-universal.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar
--------------------------------------------------------------

A member was teleporting via an enderrail from EnderIO to our main trainstation. While he was teleporting the server crashed.

**Comment by utoc** [comment]
Hello,

I too had this issue tonight.  FML 1401.  Crashlog: http://pastebin.com/91P80sBV

WR-CBE 1.4.1.9
CodeChickenCore 1.0.6.43

Someone was porting into a new rfTools dimension and the server crashed with the aforementioned error.

**Comment by utoc** [comment]
Greetings,

I have another crashlog on this issue to report, http://pastebin.com/UvLd003C

FML 1448, WR-CBE 1.4.1.9 and CodeChickenCore 1.0.7.46.  I am running FastCraft.  This happened again when someone was using an rfTools matter transmitter in the same dimension.

**Comment by joserobjr** [comment]
Just for reference: @Terpos's log:
```java
Description: Exception in server tick loop
 
java.lang.NullPointerException: Exception in server tick loop
at codechicken.wirelessredstone.addons.RedstoneEtherServerAddons.deactivateRemote(RedstoneEtherServerAddons.java:84)
at codechicken.wirelessredstone.addons.RedstoneEtherServerAddons.onDimensionChange(RedstoneEtherServerAddons.java:210)
at codechicken.wirelessredstone.addons.WRAddonEventHandler.playerDimensionChange(WRAddonEventHandler.java:35)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_436_WRAddonEventHandler_playerDimensionChange_PlayerChangedDimensionEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at cpw.mods.fml.common.FMLCommonHandler.firePlayerChangedDimensionEvent(FMLCommonHandler.java:545)
at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:504)
at crazypants.enderio.rail.PlayerTeleportHandler$TeleportAction.doTeleport(PlayerTeleportHandler.java:81)
at crazypants.enderio.rail.PlayerTeleportHandler.onServerTick(PlayerTeleportHandler.java:29)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_224_PlayerTeleportHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

@utoc's log 1
```java
Description: Ticking block entity
 
java.lang.NullPointerException: Ticking block entity
        at codechicken.wirelessredstone.addons.RedstoneEtherServerAddons.deactivateRemote(RedstoneEtherServerAddons.java:84)
        at codechicken.wirelessredstone.addons.RedstoneEtherServerAddons.onDimensionChange(RedstoneEtherServerAddons.java:210)
        at codechicken.wirelessredstone.addons.WRAddonEventHandler.playerDimensionChange(WRAddonEventHandler.java:35)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_527_WRAddonEventHandler_playerDimensionChange_PlayerChangedDimensionEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerChangedDimensionEvent(FMLCommonHandler.java:545)
        at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:517)
        at mcjty.rftools.blocks.teleporter.TeleportationTools.teleportToDimension(TeleportationTools.java:294)
        at mcjty.rftools.blocks.teleporter.TeleportationTools.performTeleport(TeleportationTools.java:125)
        at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.performTeleport(MatterTransmitterTileEntity.java:487)
        at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.checkStateServer(MatterTransmitterTileEntity.java:348)
        at mcjty.entity.GenericTileEntity.func_145845_h(GenericTileEntity.java:44)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- Block entity being ticked --
Details:
        Name: MatterTransmitterTileEntity // mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity
        Block type: ID #2007 (tile.matterTransmitterBlock // mcjty.rftools.blocks.teleporter.MatterTransmitterBlock)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (447,68,263), Chunk: (at 15,4,7 in 27,16; contains blocks 432,0,256 to 447,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
        Actual block type: ID #2007 (tile.matterTransmitterBlock // mcjty.rftools.blocks.teleporter.MatterTransmitterBlock)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
```

@utoc's log 2
```java
Description: Ticking block entity
 
java.lang.NullPointerException: Ticking block entity
        at codechicken.wirelessredstone.addons.RedstoneEtherServerAddons.deactivateRemote(RedstoneEtherServerAddons.java:84)
        at codechicken.wirelessredstone.addons.RedstoneEtherServerAddons.onDimensionChange(RedstoneEtherServerAddons.java:210)
        at codechicken.wirelessredstone.addons.WRAddonEventHandler.playerDimensionChange(WRAddonEventHandler.java:35)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_562_WRAddonEventHandler_playerDimensionChange_PlayerChangedDimensionEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerChangedDimensionEvent(FMLCommonHandler.java:545)
        at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:517)
        at mcjty.rftools.blocks.teleporter.TeleportationTools.teleportToDimension(TeleportationTools.java:294)
        at mcjty.rftools.blocks.teleporter.TeleportationTools.performTeleport(TeleportationTools.java:125)
        at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.performTeleport(MatterTransmitterTileEntity.java:488)
        at mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity.checkStateServer(MatterTransmitterTileEntity.java:349)
        at mcjty.entity.GenericTileEntity.func_145845_h(GenericTileEntity.java:45)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- Block entity being ticked --
Details:
        Name: MatterTransmitterTileEntity // mcjty.rftools.blocks.teleporter.MatterTransmitterTileEntity
        Block type: ID #2007 (tile.matterTransmitterBlock // mcjty.rftools.blocks.teleporter.MatterTransmitterBlock)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (2994,110,2103), Chunk: (at 2,6,7 in 187,131; contains blocks 2992,0,2096 to 3007,255,2111), Region: (5,4; contains chunks 160,128 to 191,159, blocks 2560,0,2048 to 3071,255,2559)
        Actual block type: ID #2007 (tile.matterTransmitterBlock // mcjty.rftools.blocks.teleporter.MatterTransmitterBlock)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
```
