### ISSUE TITLE
NullPointerException : FTB Infinity Evolved 2.2.2

### ISSUE THREAD

**Issue by Cholesterol** [Chicken-Bones/WirelessRedstone#23]
Hey there,

Having a crash -  Logs below.  I'm typically not on when the crash occurs so hard for me to say what exactly a player is doing when this happens... but it appears to be WR related. 

http://pastebin.com/6WJaQbyy

Thanks!

**Comment by Cholesterol** [comment]
FWIW - did end up resolving the issue - this seems to occur in TPS sensitive situations when TPS drops below 20 (roughly 17 or so).

**Comment by joserobjr** [comment]
Justo for reference:
```java
Description: Exception in server tick loop
 
java.lang.NullPointerException: Exception in server tick loop
    at codechicken.wirelessredstone.core.RedstoneEtherServer.updateJammedNodes(RedstoneEtherServer.java:652)
    at codechicken.wirelessredstone.core.RedstoneEtherServer.tick(RedstoneEtherServer.java:629)
    at codechicken.wirelessredstone.core.WRCoreEventHandler.serverTick(WRCoreEventHandler.java:109)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_503_WRCoreEventHandler_serverTick_WorldTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by cha0s** [comment]
This happening on FTB Beyond 1.10.2 as well. Slightly different trace:

```
java.lang.NullPointerException: Exception in server tick loop
        at codechicken.wirelessredstone.manager.RedstoneEtherServer.updateJammedNodes(RedstoneEtherServer.java:658)
        at codechicken.wirelessredstone.manager.RedstoneEtherServer.tick(RedstoneEtherServer.java:635)
        at codechicken.wirelessredstone.handler.WREventHandler.serverTick(WREventHandler.java:159)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_648_WREventHandler_serverTick_WorldTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:718)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by BrainStone** [comment]
It looks like I'm having this issue too. When I start profiling with JER (TPS drops suuuuuper low) I get this crash: https://gist.github.com/BrainStone/6597fcaafb39b05df8301558f42d67fc
