### ISSUE TITLE
Inconsistent Crash on Startup

### ISSUE THREAD

**Issue by NeonNobility** [Chicken-Bones/WirelessRedstone#27]
**About 40% of the time I open my client, it crashes shortly before it finished loading and gives me the message "No base frame for texture: wrcbe_addons:remote_23". I'm running version 1.4.1.9 for Minecraft 1.7.10.**

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 4/20/20 3:17 AM
Description: Registering texture

java.lang.RuntimeException: No base frame for texture: wrcbe_addons:remote_23
	at codechicken.lib.render.TextureSpecial.load(TextureSpecial.java:153)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:208)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:152)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:101)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:215)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codechicken.lib.render.TextureSpecial.load(TextureSpecial.java:153)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:208)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:152)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/atlas/items.png
	Texture object class: net.minecraft.client.renderer.texture.TextureMap
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:101)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:215)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by NeonNobility** [comment]
Guess I'll die
